using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Steps_OOP_01
{

    /*
     By AbdelRazek mohamed
     All Method Need Alot Of Logic But I Tried To Implement Simple System regardless Complecated Logic
     
     */
    public class Employee
    {
        private static int AutoGeneratedID = 0;
        private int _id = 0;
        private string _name;
        private string _address;
        private string _phone;
        private double _salary;
        public Employee()
        {
            AutoGeneratedID++;
            _id = AutoGeneratedID;
        }

        
        public void SetName(string name)
        {
            if(name.Length>3 && name.Length<=20 && !String.IsNullOrWhiteSpace(name))
            {
                _name = name;
            }
            else
            {
                Console.WriteLine("Invalide Name Try Agine");
                SetName(name);
            }
        }
        public void SetAddress(string address) 
        {
            if (address.Length > 3 && address.Length <= 20 && !String.IsNullOrWhiteSpace(address))
            {
                _address = address;
            }
            else
            {
                Console.WriteLine("Invalide Address");
            }
        }
        
        public void SetPhone(string phone)
        {
            if (phone.Length == 11 && !String.IsNullOrWhiteSpace(phone))
            {
                if (phone.StartsWith("011") || phone.StartsWith("012") || phone.StartsWith("010") || phone.StartsWith("015"))
                {
                    _phone = phone;
                }
                else
                {
                    Console.WriteLine("Phone Must Be 010||011||015||012");
                }
            }
            
        }

        public void SetSalary(double salary) 
        {
            if (salary >= 6000) 
            { 
                _salary = salary;
            }
            else
            {
                Console.WriteLine("Invalide Salary");

            }
        }

        public void IncreaseSalaryFixedAmmount(double amount)
        {
            SetSalary(amount);
        }
        public void IncreaseSalaryPercentage(double percentage)
        {
            double newSalary = ((_salary / 100) * percentage) + GetSalary();
            SetSalary(newSalary);
        }
        public string GetName() { return _name; }
        public string GetAddress() { return _address; }
        public string GetPhone() { return _phone; }
        public double GetSalary() { return _salary; }
        public int GetId() { return _id; }

        public void DisplayInfo()
        {
            Console.WriteLine($"ID: {_id}");
            Console.WriteLine($"Name: {_name}");
            Console.WriteLine($"Address: {_address}");
            Console.WriteLine($"Phone: {_phone}");
            Console.WriteLine($"Salary: {_salary}");
            Console.WriteLine("*****************");
        }



    }
}
